local _, ns = ...

ns.defaults = {
    enabled             = true,
    showWhenSolo        = true,
    locked              = false,
    hideHudInCombat     = true,
    hudAlphaIdle        = 0.75,
    hudAlphaHover       = 1.0,
    hudScale            = 1.0,
    showHudNeedCount    = true,
    showTimers          = true,
    showGlow            = true,
    showSound           = false,
    showClassRows       = true,
    gridColumns         = 5,
    buffArmor           = true,
    armorType           = "auto",
    enableBubble        = true,
    bubbleType          = "auto",
    bubbleThreshold     = 50,
    buffIntellect       = true,
    useArcaneBrilliance = true,
    buffPets            = true,
    showDragHandle      = true,
    refreshFloorSec     = 120,
    hudPos              = nil,
    minimap             = { hide = false },
    migratedFromMagePower = false,
}
